#ifndef ERRORS_H
#define ERRORS_H

enum {
    PROXY_MAX_EVENTS = -7,
    PROXY_INTR,
    PROXY_CONNECT_ERR,
    PROXY_INCOMPLETE_ACCEPT,
    PROXY_WOULD_BLOCK,
    PROXY_DISCONNECT,
    PROXY_ERR,
    PROXY_SUCCESS,
};

#endif