name: Multi-Arch-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kevin-mckenzie/n-proxy:latest

    steps:
      - uses: actions/checkout@v4
      - name: lint
        run: inv lint

  build-analyze-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kevin-mckenzie/n-proxy:latest

    strategy:
      matrix:
        target: [local, valgrind, asan, linux-x86_64-musl, linux-i686-musl, linux-arm-musl, linux-arm64-musl, linux-mips-musl]
        build_type: [release, debug]
        exclude:
          - target: valgrind
            build_type: release
          - target: asan
            build_type: release
          - target: local
            build_type: release

    steps:
      - uses: actions/checkout@v4

      - name: build-${{ matrix.target }}-${{ matrix.build_type }}
        run: |
          if [ "${{ matrix.build_type }}" = "release" ]; then
            inv build --target ${{ matrix.target }} --release
          else
            inv build --target ${{ matrix.target }}
          fi

      - name: analyze-${{ matrix.target }}-${{ matrix.build_type }}
        run: |
          if [ "${{ matrix.build_type }}" = "release" ]; then
            inv analyze --target ${{ matrix.target }} --release
          else
            inv analyze --target ${{ matrix.target }}
          fi

      - name: test-${{ matrix.target }}-${{ matrix.build_type }}
        run: |
          if [ "${{ matrix.build_type }}" = "release" ]; then
            inv test --target ${{ matrix.target }} --release
          else
            inv test --target ${{ matrix.target }}
          fi

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-${{ matrix.build_type }}
          path: dist/bin/*

  package:
    needs: build-analyze-test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kevin-mckenzie/n-proxy:latest

    steps:
      - uses: actions/checkout@v4

      - name: download 
        uses: actions/download-artifact@v4
        with:
          path: dist/bin

      - name: compress
        run: tar cf nacl-proxy.tar.gz dist/bin

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: nacl-proxy.tar.gz
          path: nacl-proxy.tar.gz
